### ISSUE TITLE
Eplus streams with SAMPLE-AES unable to decrypt

### ISSUE THREAD

**Issue by Lockjaw444** [pmrowla/streamlink-plugins#16]
There have been some eplus streams recently that used sample-aes encryption which streamlink does not natively decrypt (https://github.com/streamlink/streamlink/issues/354). I suspect we will see more eplus streams using this method in the future. Looks like it was used to employ apple fairply drm. Here's the m3u8.
[index_4.txt](https://github.com/pmrowla/streamlink-plugins/files/11665659/index_4.txt)

**Comment by pmrowla** [comment]
I think this would need to be handled on the streamlink side. ffmpeg supports sample-aes decryption now (it did not when that streamlink issue was originally opened) so in theory streamlink should be able to support it now I think

edit: oh looking at the m3u8, the real problem here will be that it uses apple's DRM for key rotation. implementing sample-aes decryption is feasible, handling the DRM key exchange is probably not

**Comment by Lockjaw444** [comment]
This can be closed. There are forks of streamlink that handle drm but the official one does not.
